services:
  - type: web
    name: stock-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tradebot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_real_token_here